IF OBJECT_ID('dbo.udf_GetSKUPrice') IS NOT NULL DROP FUNCTION dbo.udf_GetSKUPrice;
GO
CREATE FUNCTION dbo.udf_GetSKUPrice
(
	@ID_SKU INT
)
RETURNS DECIMAL(18, 2)
AS
BEGIN
	DECLARE @ProdVal DECIMAL(18, 2)
	SELECT @ProdVal =  SUM([Value])/SUM(Quantity)
	FROM Basket
	GROUP BY ID_SKU
	HAVING ID_SKU = @ID_SKU
	RETURN @ProdVal
END;